---
- name: Install MsSQL on RHEL
  hosts: all
  become: yes
  vars:
    db_name: testDB
    db_host: localhost
    db_user: SA
    db_password: P@ssWORD!

  roles:
    - { role: kyleabenson.mssql }

  tasks:
    - name: Pause for 30 seconds for DB connection to come up
      pause:
        seconds: 30

    - name: Create a new database
      mssql_db:
        name: "{{ db_name }}"
        state: present
        login_host: "{{ db_host }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
